// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zozsygeulnhkufcjqyba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvenN5Z2V1bG5oa3VmY2pxeWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODc0OTksImV4cCI6MjA2MzQ2MzQ5OX0.x21jBXHRoxkheWHDtiN7PhBc3al8MnS70ykmqxALthI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);